#!/usr/bin/env bash
#if else statements for existing, non empty, regular files
if [ -e "school" ]; 
then
echo "school file is exist"
else
echo "school file does not exist"
fi
if [ -s "school" ]; 
then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f "school" ]; 
then
echo "school file is a regular file"
else
echo " "
fi